### ISSUE TITLE
Non-contiguous roads within suburb boundaries with no connection to the contiguous suburb

### ISSUE THREAD

**Issue by zdebruine** [jgc234/optiburb#3]
Opening a general issue here that's dependent on the graph-based solvers deployed in the code.  This is probably not going to be easy to fix, but it's an issue.

When there are roads within a suburb boundary that have no connection to the rest of the suburb, the entire code fails.

This will require download of OSM data surrounding the suburb, and graph-based optimization considering nodes outside of the suburb as potential (but not required) routes for traversal.

**Comment by jgc234** [comment]
osmnx has some nifty features to try and rectify this already (there's a buffer feature that looks outside the polygon then tries to contract it back down again).. I'll have a look at this and see if we can make it work. For the longer term, I was going to write my own routing engine, but that will take some time.  What's the suburb or search criteria you used so I can try and re-created your scenario?

**Comment by hdbonnett** [comment]
@ZacharyDeBruine - Are you getting an error like this?
` networkx.exception.NetworkXNoPath: Node 2633506910 not reachable from 417742848`

If so, I was seeing the same when running it for Nunawading, Victoria, Australia: (using the shapefile)
`./optiburb.py   --prune --shapefile ./VIC_LOCALITY_POLYGON_shp,VIC_LOCA_2 NUNAWADING`

I implemented a lazy workaround by adding an exception handler:
` diff optiburb.py optiburb.py.orig
 152,155c152,153
< try:
<    shortest_paths[pair] = nx.dijkstra_path_length(g, i, j, weight='length')
< except nx.NetworkXNoPath:
<  print ("Orphaned Node")
 
> shortest_paths[pair] = nx.dijkstra_path_length(g, i, j, weight='length')`

Now I'm getting a "euler_circuit=false" and subsequent NetworkXError so looking to see if I can use the same approach to run to completion. It isn't the optimal solution for certain.

**Comment by jgc234** [comment]
Remove the `--prune` and it should work for Nunawading (and also get the latest code - there were some updates to the filters a few days back, if that helps)

**Comment by hdbonnett** [comment]
Hi Jim - thanks! I'll pull a new version now and give that a go. I'm a PHP guy but keen to play with more Python since it is so popular for GIS work.

**Comment by hdbonnett** [comment]
Hmm - it ran very quickly (under 5 seconds) w/o errors but appears to have only picked up a subset of the polygon. I've pulled the gpx into QGIS and overlaid it on the polygon from the shape file. It looks like the algorithms decided that the rail line and Springvale road weren't crossable.
![Nunawading](https://user-images.githubusercontent.com/19419731/89237415-705de080-d636-11ea-822e-1bd60b83798b.png)

**Comment by jgc234** [comment]
@hdbonnett - Yeah, I can see that problem too.. I think the problem is Springvale Rd being classified as highway=trunk, but we've got a filter in there to exclude it, so the partitions the whole suburb into two parts, and discards the east side.  Similarly for crossing the railway line to the south (via the crossing at Springvale Rd).   Try removing the trunk and trunk_link (I'm running it now and it's taking significantly longer than 5 seconds... 

```python
            #'["highway"!~"motorway|motorway_link|trunk|trunk_link|bridleway|footway|service|pedestrian|'
            '["highway"!~"motorway|motorway_link|bridleway|footway|service|pedestrian|'
```

**Comment by hdbonnett** [comment]
Got it - I'll do that on my end too.
PS: My suburb (Eltham) ran for over an hour and ended up at 186km and 2,666m! Not gonna be under one hour for that ;-)

**Comment by jgc234** [comment]
@hdbonnett - Mine ran and looks OK (84.5km).  If you want to be really picky, you might want to add `--buffer=10` or something similar to fix the boundary near Esdale Street (the polygon boundary cuts off the end of the street, so it doesn't get included).  

Re Eltham, yeah, you'd better ride faster (like 186km/h).. Maybe a feature to split up the GPX into parts?.. which would look ugly.. so maybe a feature to segment the suburb into clean chunks first.

Another interesting idea.. You can build a 5km radius by specifying your exact address (instead of a suburb) and --`buffer=5000`.  Mine's taken 12 hours of processing so far and it's only 70% of the way there.

**Comment by hdbonnett** [comment]
Thanks! It ran for me as well and returned 85.1km for Nunawading. I'll send it off to the requestor (I've offered to run it for some others).
The crazy thing is that that 186km track is all within 5km of my house!

**Comment by BrianDScott** [comment]
Using --prune --shapefile /usr/local/share/optiburb/VIC_LOCALITY_POLYGON_shp,VIC_LOCA_2 TAWONGA
produces the same node xxx not reachable from yyyy error mentioned above. Removing prune runs to completion but includes dirt tracks that you wouldn't send a goat up.
Doing the 5km radius version runs OK with prune but still includes some dirt tracks I'd have trouble walking up much less cycling. Looking deeper, the debug output shows that the code is still selecting edges that are track/unpaved or track/-. This is probably a separate issue.

**Comment by jgc234** [comment]
@BrianDScott - wow, you're testing the boundaries there with Tawonga - not quite your typical suburban setting.. The idea of `--prune` was to remove tracks without names, which works well where I live. If someone gave your goat track a nice name, then you'll have to work out another tag to filter on.  If you're ok with OSM and QGIS then you can fiddle around and find them.. Otherwise, tell me a few track names and I'll see if I can work it out..  I might have to fix up the `--prune` option to fail nicely and try a bit harder to recover.

**Comment by BrianDScott** [comment]
Just looking at the debug messages from print_edges for some examples:
print_edges:239 [DEBUG] 701768326  Ryder Spur Track               track                -
print_edges:239 [DEBUG] 47345135   Mountain Creek Road            unclassified         unpaved
print_edges:239 [DEBUG] 701760671  Eskdale Spur Track             track                -
print_edges:239 [DEBUG] 47345464   Fieldings Road                 unclassified         unpaved

but then there are also some roads like:
print_edges:239 [DEBUG] 107255149  Drummond Street                residential          -
that has been perfectly sealed for as long as I can remember. I don't think you could perfectly deal with the data quality in OSM so I there may be some limitations to this.

**Comment by hdbonnett** [comment]
> Another interesting idea.. You can build a 5km radius by specifying your exact address
I've just started mine running now.. Given the 186km Burbing was all within the 5km, I suspect it will turn out to be pretty epic ;-)

**Comment by jgc234** [comment]
> I've just started mine running now.. Given the 186km Burbing was all within the 5km, I suspect it will turn out to be pretty epic ;-)

Mine took 22 hours to process and turned out to be 711km..  I reckon I need a function to split the suburb or circle into smaller polygons - it will process faster then, and also more feasible to ride in chunks.. Not sure how to approach that yet though.

**Comment by hdbonnett** [comment]
> Mine took 22 hours to process and turned out to be 711km..  
Ouch.. That's one way to keep yourself busy on the bike! 

Somewhat related, I've spent a bit of time looking at the work going on to add elevation/slope to the OSRM/OSM data (http://www.liedman.net/2015/04/13/add-elevation-data-to-osrm/) but haven't had the bandwidth to go any further. Maybe when less busy (heh)
